import { promises as fs } from 'fs';
import path from 'path';
import { GeneratedTest, TestWriteResult } from './types.js';

export class TestWriter {
  constructor(private metadataDirName: string = '.metadata') {}

  async writeTests(testsRoot: string, tests: GeneratedTest[], language?: string): Promise<TestWriteResult> {
    const writtenFiles: string[] = [];
    const metadataFiles: string[] = [];
    const metaDir = path.join(testsRoot, this.metadataDirName);
    await fs.mkdir(metaDir, { recursive: true });

    // 🧬 STRATEGY: Single class file with multiple test methods (accumulation mode)
    const lang = language || tests[0]?.metadata.language || 'unknown';
    
    if (lang === 'java' && tests.length > 0) {
      // For Java: merge all tests into a single class file
      const mergedFile = await this.mergeJavaTests(testsRoot, tests);
      writtenFiles.push(mergedFile);
    } else {
      // For other languages: keep individual files (for now)
      for (const test of tests) {
        const ext = this.extForLanguage(lang);
        const fileName = `${test.name}${ext}`;
        const filePath = path.join(testsRoot, fileName);
        await fs.writeFile(filePath, this.wrapTestCode(test, lang));
        writtenFiles.push(filePath);
      }
    }

    // Write metadata for all tests
    for (const test of tests) {
      const metaPath = path.join(metaDir, `${test.name}.meta.json`);
      
      // Extract package from test code for Java
      let packageName: string | undefined;
      if (language === 'java' || test.metadata.language === 'java') {
        const packageMatch = test.code.match(/package\s+([\w.]+);/);
        if (packageMatch) {
          packageName = packageMatch[1];
        }
      }
      
      const metaContent = {
        sourceFile: test.metadata.targetFile,
        generatedAt: new Date().toISOString(),
        evolutionGeneration: test.metadata.generation || 0,
        fitnessScore: null,
        coverage: null,
        testedMethods: test.metadata.targetMethod ? [test.metadata.targetMethod] : [],
        origin: test.metadata.origin,
        language: language || test.metadata.language,
        package: packageName
      };
      await fs.writeFile(metaPath, JSON.stringify(metaContent, null, 2));
      metadataFiles.push(metaPath);
    }

    return { writtenFiles, metadataFiles };
  }

  private extForLanguage(lang: string): string {
    switch (lang) {
      case 'java': return '.java';
      case 'python': return '.py';
      case 'typescript': return '.test.ts';
      case 'javascript': return '.test.js';
      case 'rust': return '.rs';
      default: return '.txt';
    }
  }

  private wrapTestCode(test: GeneratedTest, _lang?: string): string {
    // Provide a basic header comment for traceability.
    return `/* Generated by Monkey-Fuzzingo (origin=${test.metadata.origin}, target=${test.metadata.targetFile}) */\n${test.code}\n`;
  }

  /**
   * 🧬 Merge multiple Java tests into a single class file
   * Each test becomes a method in the class, accumulating across generations
   */
  private async mergeJavaTests(testsRoot: string, tests: GeneratedTest[]): Promise<string> {
    // Extract package from first test
    const firstTest = tests[0];
    const packageMatch = firstTest.code.match(/package\s+([\w.]+);/);
    const packageName = packageMatch ? packageMatch[1] : 'generated';
    
    // Extract class name from target file
    const targetFileMatch = firstTest.metadata.targetFile.match(/([A-Z]\w+)\.java$/);
    const className = targetFileMatch ? `${targetFileMatch[1]}Test` : 'GeneratedTest';
    
    // Extract imports from all tests (deduplicate)
    const allImports = new Set<string>();
    for (const test of tests) {
      const imports = test.code.match(/^import\s+.+;$/gm) || [];
      imports.forEach(imp => allImports.add(imp));
    }
    
    // Extract test methods from all tests
    const testMethods: string[] = [];
    for (const test of tests) {
      // Extract method from test code (remove package, imports, class wrapper)
      const methodMatch = test.code.match(/@Test[\s\S]*?(?=\n\s*(@Test|}))/);
      if (methodMatch) {
        const methodWithComment = `    /* ${test.metadata.origin} - Gen ${test.metadata.generation || 0} */\n    ${methodMatch[0].trim()}`;
        testMethods.push(methodWithComment);
      } else {
        // Fallback: extract entire method body
        const simpleMethod = test.code.match(/@Test\s+void\s+\w+\([^)]*\)[^{]*\{[\s\S]*?\n\s*\}/);
        if (simpleMethod) {
          testMethods.push(`    ${simpleMethod[0].trim()}`);
        }
      }
    }
    
    // Build complete class
    const classContent = `/* Generated by Monkey-Fuzzingo - Evolutionary Test Suite */
package ${packageName};

${Array.from(allImports).join('\n')}

class ${className} {

${testMethods.join('\n\n')}

}
`;
    
    // Write to file
    const fileName = `${className}.java`;
    const filePath = path.join(testsRoot, fileName);
    await fs.writeFile(filePath, classContent);
    
    return filePath;
  }
}
