import { promises as fs } from 'fs';
import path from 'path';
import { GeneratedTest, TestWriteResult } from './types.js';

export class TestWriter {
  constructor(private metadataDirName: string = '.metadata') {}

  async writeTests(testsRoot: string, tests: GeneratedTest[], language?: string): Promise<TestWriteResult> {
    const writtenFiles: string[] = [];
    const metadataFiles: string[] = [];
    const metaDir = path.join(testsRoot, this.metadataDirName);
    await fs.mkdir(metaDir, { recursive: true });

    for (const test of tests) {
      // Determine file extension based on language (very simple heuristic)
      const ext = this.extForLanguage(language || test.metadata.language || 'unknown');
      const fileName = `${test.name}${ext}`;
      const filePath = path.join(testsRoot, fileName);
      await fs.writeFile(filePath, this.wrapTestCode(test, language || test.metadata.language));
      writtenFiles.push(filePath);

      const metaPath = path.join(metaDir, `${test.name}.meta.json`);
      const metaContent = {
        sourceFile: test.metadata.targetFile,
        generatedAt: new Date().toISOString(),
        evolutionGeneration: test.metadata.generation || 0,
        fitnessScore: null,
        coverage: null,
        testedMethods: test.metadata.targetMethod ? [test.metadata.targetMethod] : [],
        origin: test.metadata.origin,
        language: language || test.metadata.language
      };
      await fs.writeFile(metaPath, JSON.stringify(metaContent, null, 2));
      metadataFiles.push(metaPath);
    }

    return { writtenFiles, metadataFiles };
  }

  private extForLanguage(lang: string): string {
    switch (lang) {
      case 'java': return '.java';
      case 'python': return '.py';
      case 'typescript': return '.test.ts';
      case 'javascript': return '.test.js';
      case 'rust': return '.rs';
      default: return '.txt';
    }
  }

  private wrapTestCode(test: GeneratedTest, _lang?: string): string {
    // Provide a basic header comment for traceability.
    return `/* Generated by Monkey-Fuzzingo (origin=${test.metadata.origin}, target=${test.metadata.targetFile}) */\n${test.code}\n`;
  }
}
