import { promises as fs } from 'fs';
import path from 'path';
export class TestWriter {
    constructor(metadataDirName = '.metadata') {
        this.metadataDirName = metadataDirName;
    }
    async writeTests(testsRoot, tests, language) {
        const writtenFiles = [];
        const metadataFiles = [];
        const metaDir = path.join(testsRoot, this.metadataDirName);
        await fs.mkdir(metaDir, { recursive: true });
        // 🧬 STRATEGY: Single class file with multiple test methods (accumulation mode)
        const lang = language || tests[0]?.metadata.language || 'unknown';
        if (lang === 'java' && tests.length > 0) {
            // For Java: merge all tests into a single class file
            const mergedFile = await this.mergeJavaTests(testsRoot, tests);
            writtenFiles.push(mergedFile);
        }
        else {
            // For other languages: keep individual files (for now)
            for (const test of tests) {
                const ext = this.extForLanguage(lang);
                const fileName = `${test.name}${ext}`;
                const filePath = path.join(testsRoot, fileName);
                await fs.writeFile(filePath, this.wrapTestCode(test, lang));
                writtenFiles.push(filePath);
            }
        }
        // Write metadata for all tests
        for (const test of tests) {
            const metaPath = path.join(metaDir, `${test.name}.meta.json`);
            // Extract package from test code for Java
            let packageName;
            if (language === 'java' || test.metadata.language === 'java') {
                const packageMatch = test.code.match(/package\s+([\w.]+);/);
                if (packageMatch) {
                    packageName = packageMatch[1];
                }
            }
            const metaContent = {
                sourceFile: test.metadata.targetFile,
                generatedAt: new Date().toISOString(),
                evolutionGeneration: test.metadata.generation || 0,
                fitnessScore: null,
                coverage: null,
                testedMethods: test.metadata.targetMethod ? [test.metadata.targetMethod] : [],
                origin: test.metadata.origin,
                language: language || test.metadata.language,
                package: packageName
            };
            await fs.writeFile(metaPath, JSON.stringify(metaContent, null, 2));
            metadataFiles.push(metaPath);
        }
        return { writtenFiles, metadataFiles };
    }
    extForLanguage(lang) {
        switch (lang) {
            case 'java': return '.java';
            case 'python': return '.py';
            case 'typescript': return '.test.ts';
            case 'javascript': return '.test.js';
            case 'rust': return '.rs';
            default: return '.txt';
        }
    }
    wrapTestCode(test, _lang) {
        // Provide a basic header comment for traceability.
        return `/* Generated by Monkey-Fuzzingo (origin=${test.metadata.origin}, target=${test.metadata.targetFile}) */\n${test.code}\n`;
    }
    /**
     * 🧬 Build Java test class from structured metadata (language-agnostic approach)
     * Uses JSON structure instead of regex parsing
     */
    buildJavaClassFromStructure(structure) {
        const { className, package: pkg, imports, fields = [], methods } = structure;
        const importLines = imports.map(imp => imp.trim()).join('\n');
        const fieldLines = fields.map(f => `    ${f.trim()}`).join('\n');
        const methodLines = methods.map(method => {
            const comment = method.origin ? `    /* ${method.origin} - Gen ${method.generation || 0} */` : '';
            const annotations = method.annotations ? method.annotations.map(a => `    ${a}`).join('\n') : '';
            const signature = `    ${method.signature}`;
            const body = method.body.split('\n').map(line => `        ${line}`).join('\n');
            return `${comment}
${annotations}
${signature} {
${body}
    }`;
        }).join('\n\n');
        return `/* Generated by Monkey-Fuzzingo - Evolutionary Test Suite */
package ${pkg};

${importLines}

class ${className} {

${fieldLines}

${methodLines}
}
`;
    }
    /**
     * 🧬 Merge multiple Java tests into a single class file
     * Each test becomes a method in the class, accumulating across generations
     *
     * Uses structured extraction (compatible with both raw code and Copilot JSON)
     */
    async mergeJavaTests(testsRoot, tests) {
        // Extract package from first test
        const firstTest = tests[0];
        const packageMatch = firstTest.code.match(/package\s+([\w.]+);/);
        const packageName = packageMatch ? packageMatch[1] : 'generated';
        // Extract class name from target file
        const targetFileMatch = firstTest.metadata.targetFile.match(/([A-Z]\w+)\.java$/);
        const className = targetFileMatch ? `${targetFileMatch[1]}Test` : 'GeneratedTest';
        // 🧠 Parse structured components from existing test code
        const structure = this.parseJavaTestStructure(tests, packageName, className);
        // 🏗️ Build class using structured approach
        const classContent = this.buildJavaClassFromStructure(structure);
        // Write to file
        const fileName = `${className}.java`;
        const filePath = path.join(testsRoot, fileName);
        await fs.writeFile(filePath, classContent);
        return filePath;
    }
    /**
     * 📐 Parse Java test structure from raw code (backward compatible)
     * Extracts: package, imports, fields, methods
     */
    parseJavaTestStructure(tests, packageName, className) {
        const allImports = new Set();
        const allFields = new Set();
        const methods = [];
        for (const test of tests) {
            const code = test.code;
            // Extract imports
            const imports = code.match(/^import\s+.+;$/gm) || [];
            imports.forEach(imp => allImports.add(imp.trim()));
            // Extract fields (@Mock, @InjectMocks, private fields)
            const fieldMatches = code.match(/@(?:Mock|InjectMocks|Autowired|Value)\s+(?:private|protected|public)?\s+\w+(?:<[^>]+>)?\s+\w+;/g) ||
                code.match(/(?:private|protected|public)\s+\w+(?:<[^>]+>)?\s+\w+;/g) || [];
            fieldMatches.forEach(field => allFields.add(field.trim()));
            // Extract test method (improved regex with fallback)
            const methodMatch = code.match(/@Test[\s\S]*?void\s+(\w+)\s*\([^)]*\)(?:\s+throws\s+[\w,\s]+)?\s*\{([\s\S]*?)\n\s*\}/);
            if (methodMatch) {
                const methodName = methodMatch[1];
                const methodBody = methodMatch[2];
                const throwsClause = code.match(/void\s+\w+\s*\([^)]*\)\s+(throws\s+[\w,\s]+)/)?.[1] || '';
                methods.push({
                    name: methodName,
                    annotations: ['@Test'],
                    signature: `void ${methodName}()${throwsClause ? ' ' + throwsClause : ''}`,
                    body: methodBody.trim(),
                    origin: test.metadata.origin,
                    generation: test.metadata.generation || 0
                });
            }
            else {
                console.warn(`⚠️ Could not extract method from test: ${test.name}`);
            }
        }
        return {
            className,
            package: packageName,
            imports: Array.from(allImports),
            fields: Array.from(allFields),
            methods
        };
    }
}
