import { promises as fs } from 'fs';
import path from 'path';
import { GeneratedTest, TestWriteResult } from './types.js';

export class TestWriter {
  constructor(private metadataDirName: string = '.metadata') {}

  async writeTests(testsRoot: string, tests: GeneratedTest[], language?: string): Promise<TestWriteResult> {
    const writtenFiles: string[] = [];
    const metadataFiles: string[] = [];
    const metaDir = path.join(testsRoot, this.metadataDirName);
    await fs.mkdir(metaDir, { recursive: true });

    // 🧬 STRATEGY: Single class file with multiple test methods (accumulation mode)
    const lang = language || tests[0]?.metadata.language || 'unknown';
    
    if (lang === 'java' && tests.length > 0) {
      // For Java: merge all tests into a single class file
      const mergedFile = await this.mergeJavaTests(testsRoot, tests);
      writtenFiles.push(mergedFile);
    } else {
      // For other languages: keep individual files (for now)
      for (const test of tests) {
        const ext = this.extForLanguage(lang);
        const fileName = `${test.name}${ext}`;
        const filePath = path.join(testsRoot, fileName);
        await fs.writeFile(filePath, this.wrapTestCode(test, lang));
        writtenFiles.push(filePath);
      }
    }

    // Write metadata for all tests
    for (const test of tests) {
      const metaPath = path.join(metaDir, `${test.name}.meta.json`);
      
      // Extract package from test code for Java
      let packageName: string | undefined;
      if (language === 'java' || test.metadata.language === 'java') {
        const packageMatch = test.code.match(/package\s+([\w.]+);/);
        if (packageMatch) {
          packageName = packageMatch[1];
        }
      }
      
      const metaContent = {
        sourceFile: test.metadata.targetFile,
        generatedAt: new Date().toISOString(),
        evolutionGeneration: test.metadata.generation || 0,
        fitnessScore: null,
        coverage: null,
        testedMethods: test.metadata.targetMethod ? [test.metadata.targetMethod] : [],
        origin: test.metadata.origin,
        language: language || test.metadata.language,
        package: packageName
      };
      await fs.writeFile(metaPath, JSON.stringify(metaContent, null, 2));
      metadataFiles.push(metaPath);
    }

    return { writtenFiles, metadataFiles };
  }

  private extForLanguage(lang: string): string {
    switch (lang) {
      case 'java': return '.java';
      case 'python': return '.py';
      case 'typescript': return '.test.ts';
      case 'javascript': return '.test.js';
      case 'rust': return '.rs';
      default: return '.txt';
    }
  }

  private wrapTestCode(test: GeneratedTest, _lang?: string): string {
    // Provide a basic header comment for traceability.
    return `/* Generated by Monkey-Fuzzingo (origin=${test.metadata.origin}, target=${test.metadata.targetFile}) */\n${test.code}\n`;
  }

  /**
   * 🧬 Build Java test class from structured metadata (language-agnostic approach)
   * Uses JSON structure instead of regex parsing
   */
  private buildJavaClassFromStructure(structure: {
    className: string;
    package: string;
    imports: string[];
    fields?: string[];
    methods: Array<{
      name: string;
      annotations?: string[];
      signature: string;
      body: string;
      origin?: string;
      generation?: number;
    }>;
  }): string {
    const { className, package: pkg, imports, fields = [], methods } = structure;

    const importLines = imports.map(imp => imp.trim()).join('\n');
    const fieldLines = fields.map(f => `    ${f.trim()}`).join('\n');
    const methodLines = methods.map(method => {
      const comment = method.origin ? `    /* ${method.origin} - Gen ${method.generation || 0} */` : '';
      const annotations = method.annotations ? method.annotations.map(a => `    ${a}`).join('\n') : '';
      const signature = `    ${method.signature}`;
      const body = method.body.split('\n').map(line => `        ${line}`).join('\n');
      
      return `${comment}
${annotations}
${signature} {
${body}
    }`;
    }).join('\n\n');

    return `/* Generated by Monkey-Fuzzingo - Evolutionary Test Suite */
package ${pkg};

${importLines}

class ${className} {

${fieldLines}

${methodLines}
}
`;
  }

  /**
   * 🧬 Merge multiple Java tests into a single class file
   * Each test becomes a method in the class, accumulating across generations
   * 
   * Uses structured extraction (compatible with both raw code and Copilot JSON)
   */
  private async mergeJavaTests(testsRoot: string, tests: GeneratedTest[]): Promise<string> {
    // Extract package from first test
    const firstTest = tests[0];
    const packageMatch = firstTest.code.match(/package\s+([\w.]+);/);
    const packageName = packageMatch ? packageMatch[1] : 'generated';
    
    // Extract class name from target file
    const targetFileMatch = firstTest.metadata.targetFile.match(/([A-Z]\w+)\.java$/);
    const className = targetFileMatch ? `${targetFileMatch[1]}Test` : 'GeneratedTest';
    
    // 🧠 Parse structured components from existing test code
    const structure = this.parseJavaTestStructure(tests, packageName, className);
    
    // 🏗️ Build class using structured approach
    const classContent = this.buildJavaClassFromStructure(structure);
    
    // Write to file
    const fileName = `${className}.java`;
    const filePath = path.join(testsRoot, fileName);
    await fs.writeFile(filePath, classContent);
    
    return filePath;
  }

  /**
   * 📐 Parse Java test structure from raw code (backward compatible)
   * Extracts: package, imports, fields, methods
   * Handles both: standalone methods AND full class definitions
   */
  private parseJavaTestStructure(tests: GeneratedTest[], packageName: string, className: string): {
    className: string;
    package: string;
    imports: string[];
    fields: string[];
    methods: Array<{
      name: string;
      annotations: string[];
      signature: string;
      body: string;
      origin: string;
      generation: number;
    }>;
  } {
    const allImports = new Set<string>();
    const allFields = new Set<string>();
    const methods: any[] = [];

    for (const test of tests) {
      const code = test.code;

      // Extract imports
      const imports = code.match(/^import\s+.+;$/gm) || [];
      imports.forEach(imp => allImports.add(imp.trim()));

      // Extract fields (@Mock, @InjectMocks, private fields, @BeforeEach setup)
      const fieldMatches = code.match(/@(?:Mock|InjectMocks|Autowired|Value)\s+(?:private|protected|public)?\s+\w+(?:<[^>]+>)?\s+\w+;/g) ||
                          code.match(/(?:private|protected|public)\s+\w+(?:<[^>]+>)?\s+\w+;/g) || [];
      fieldMatches.forEach(field => allFields.add(field.trim()));

      // Extract ALL @Test methods from the code (may be multiple per file)
      const testMethodRegex = /@Test[\s\S]*?void\s+(\w+)\s*\([^)]*\)(?:\s+throws\s+[\w,\s]+)?\s*\{/g;
      let match;
      
      while ((match = testMethodRegex.exec(code)) !== null) {
        const methodName = match[1];
        const methodSignatureEnd = match.index + match[0].length;
        
        // Find matching closing brace using bracket counting
        let braceCount = 1;
        let bodyEnd = methodSignatureEnd;
        for (let i = methodSignatureEnd; i < code.length; i++) {
          if (code[i] === '{') braceCount++;
          if (code[i] === '}') {
            braceCount--;
            if (braceCount === 0) {
              bodyEnd = i;
              break;
            }
          }
        }
        
        const methodBody = code.substring(methodSignatureEnd, bodyEnd).trim();
        const throwsMatch = match[0].match(/throws\s+([\w,\s]+)/);
        const throwsClause = throwsMatch ? `throws ${throwsMatch[1].trim()}` : '';
        
        methods.push({
          name: methodName,
          annotations: ['@Test'],
          signature: `void ${methodName}() ${throwsClause}`.trim(),
          body: methodBody,
          origin: test.metadata.origin,
          generation: test.metadata.generation || 0
        });
      }

      if (methods.length === 0) {
        console.warn(`⚠️ Could not extract any @Test methods from: ${test.name}`);
      }
    }

    console.log(`✅ Extracted ${methods.length} test methods from ${tests.length} test files`);

    return {
      className,
      package: packageName,
      imports: Array.from(allImports),
      fields: Array.from(allFields),
      methods
    };
  }
}
